= RCA: TITLE

[width="80%",cols=">s,e"]
|=====================================================
| **Incident date**               |
| **Public start time**           |
| **Public end time**             |
| **Duration (public impact)**    |
| **Duration (internal impact)**  |
| **Type of outage**              |
|=====================================================


== Symptoms/Impact

Publicly to users:

* List impacts or symptoms perceivable by users

Internally/systems:

* List impacts or symptoms that impacted technical staff

If you have different types of users (e.g. anonymous user, regular user,
administrator, etc.) then you should list the possible impacts to each of
them if different functionality may have impacted them.

* Paste command output that demonstrates when a pertinent system condition
  was met as evidence.

== Timeline

* Describe the timeline of events as they are understood.
* Ensure that neutral wording is used. Remove specific references to people by name,
  but use role in the event to differentiate actors.
* Remember the purpose is to find what processes or systems need fixing not assign
  blame to people or teams.
* Either use timestamped events in the same timezone (UTC unless otherwise specified)
  in a rough sequence (in distributed systems we can't do this perfectly only approximately)
  or if you have a good understanding of the casual timeline, use the causal timeline without
  timestamps.
* The timeline should include when alerts or escalations occurred as this will be useful to
  determine if (a) the already set process was followed; (b) when the process was violated and
  so we can understand why that was; (c) if the current escalation process works for this case
  and why (not).
* The timeline should include events that may have lead to the outage even if the event happened
  hours, days, or weeks before.
* Link to chat logs, incident reports, monitoring tool alerts, or supporting materials that are
  somewhat permanent (kept for at least 3 months at those links).

== Takeaways

* What could we do better?
* What efforts should we prioritize as a result?
* Is this likely to bite us in the ass again? How likely?
* Can we determine these problems earlier in our delivery pipeline? If so where?
* Can we add pre- and post- conditions to steps in our deploy or CI builds to flag problems before
  deploying problem builds? What about invariant conditions? Have these changed with a new component
  or feature addition, our data, or our scale?

== Next Steps

* Link to artifacts (e.g. tickets/issues, etc) capturing the next steps.

