== Documentation

This document describes the uses, purposes, and workflows of producing
meaningful technical documentation that doesn't go stale and provides
the whole team and even people external to the team value.

=== Goals and Philosophy

These document templates are intended to help serve two purposes:

* Provide a way to share context among team members of one team or
  across teams
* Aid the thought process of the experimenters. In particular, set
  the understanding and expectation that rejecting a hypothesis based
  on results from an experiment is only bad if nothing is learned from
  the resulting analysis.

=== Document Types

The following are types of documents that, when structured well but
without too much arduous restriction on prose (just meaning and clarity
of communication), offer engineering teams value from shared knowledge,
understanding, and vision:

* link:EXPERIMENT.adoc[] - this document offers a template to define
  an experiment, which could be a new feature, a refactoring of existing
  functionality, investigation into on-going and unresolved system failures,
  performance tuning, and other activities that require more scope and
  definition than the typical Jira ticket from a technical perspective.
* link:REQUIREMENTS.adoc[] - this document offers a template for aiding
  requirements gathering.
* link:PROJECT.adoc[] - this document uses the link:EXPERIMENT.adoc[]
  template for projects. This should be used when you need to gather
  requirements from stakeholders, the resource spend to undertake the
  initiative is significant, or it requires long term utilization of
  resources.
* ARCHITECTURE.adoc (coming soon) - this document offers a template to
  communicate the architecture of a service or set of collaborating
  services.
* RUNBOOK.adoc (coming soon) - this document is a template for writing
  runbooks of a specific service or peice of infrastructure.

=== Living Documentation

Make your documentation _living_.  Lower the barrier to entry by providing
basic templates in a low fuss ASCII markup language like Markdown,
Asciidoc, Textile, etc. People can then use their favorite editor to
make changes instead of spending time learning a new tool.

=== Reviews

Use code reviews for documentation. This encourages feedback and is a
familiar environment for engineers. It will make it easier to iterate,
provide line-by-line feedback, and reduce the number of different
processes involved in maintaining a project. Ideally a feature changeset
can include both the implementation and required documentation together.

=== Publishing

Enabling access to these can require tooling. If you are already using an
existing document store you should consider writing automation to publish
into that.
